import unittest
from utils import remove_brackets
from utils import cleanse_lyrics, count_words

class TestUtils(unittest.TestCase):

    def test_remove_brackets(self):
        input_string = "[Verse 1]\nWords are flowing out like endless rain into a paper cup\nThey slither wildly as they slip away across the universe\nPools of sorrow, waves of joy are drifting through my opened mind\nPossessing and caressing me\n\n[Chorus]\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\n[Verse 2]\nImages of broken light which dance before me like a million eyes\nThey call me on and on across the universe\nThoughts meander like a restless wind inside a letter box\nThey tumble blindly as they make their way across the universe\n\n[Chorus]\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n[Verse 3]\nSounds of laughter, shades of life are ringing through my open ears\nInciting and inviting me\nLimitless undying love which shines around me like a million suns\nIt calls me on and on across the universe\n\n[Chorus]\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\n[Outro]\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva"
        expected_output = "\nWords are flowing out like endless rain into a paper cup\nThey slither wildly as they slip away across the universe\nPools of sorrow, waves of joy are drifting through my opened mind\nPossessing and caressing me\n\n\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\n\nImages of broken light which dance before me like a million eyes\nThey call me on and on across the universe\nThoughts meander like a restless wind inside a letter box\nThey tumble blindly as they make their way across the universe\n\n\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\nSounds of laughter, shades of life are ringing through my open ears\nInciting and inviting me\nLimitless undying love which shines around me like a million suns\nIt calls me on and on across the universe\n\n\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\n\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva"
        result = remove_brackets(input_string)
        self.assertEqual(result, expected_output)

    def test_cleanse_lyrics(self):
        input_string = "[Verse 1]\nWords are flowing out like endless rain into a paper cup\nThey slither wildly as they slip away across the universe\nPools of sorrow, waves of joy are drifting through my opened mind\nPossessing and caressing me\n\n[Chorus]\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\n[Verse 2]\nImages of broken light which dance before me like a million eyes\nThey call me on and on across the universe\nThoughts meander like a restless wind inside a letter box\nThey tumble blindly as they make their way across the universe\n\n[Chorus]\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n[Verse 3]\nSounds of laughter, shades of life are ringing through my open ears\nInciting and inviting me\nLimitless undying love which shines around me like a million suns\nIt calls me on and on across the universe\n\n[Chorus]\nJai Guru Deva, Om\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\nNothing's gonna change my world\n\n[Outro]\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva\nJai Guru Deva"
        expected_output = "Words are flowing out like endless rain into a paper cup They slither wildly as they slip away across the universe Pools of sorrow, waves of joy are drifting through my opened mind Possessing and caressing me Jai Guru Deva, Om Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Images of broken light which dance before me like a million eyes They call me on and on across the universe Thoughts meander like a restless wind inside a letter box They tumble blindly as they make their way across the universe Jai Guru Deva, Om Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Sounds of laughter, shades of life are ringing through my open ears Inciting and inviting me Limitless undying love which shines around me like a million suns It calls me on and on across the universe Jai Guru Deva, Om Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Jai Guru Deva Jai Guru Deva Jai Guru Deva Jai Guru Deva Jai Guru Deva Jai Guru Deva"
        result = cleanse_lyrics(input_string)
        self.assertEqual(result, expected_output)

    def test_count_words(self):
        input_string = "Words are flowing out like endless rain into a paper cup They slither wildly as they slip away across the universe Pools of sorrow, waves of joy are drifting through my opened mind Possessing and caressing me Jai Guru Deva, Om Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Images of broken light which dance before me like a million eyes They call me on and on across the universe Thoughts meander like a restless wind inside a letter box They tumble blindly as they make their way across the universe Jai Guru Deva, Om Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Sounds of laughter, shades of life are ringing through my open ears Inciting and inviting me Limitless undying love which shines around me like a million suns It calls me on and on across the universe Jai Guru Deva, Om Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Nothing's gonna change my world Jai Guru Deva Jai Guru Deva Jai Guru Deva Jai Guru Deva Jai Guru Deva Jai Guru Deva"
        expected_output = 205
        result = count_words(input_string)
        self.assertEqual(result, expected_output)

if __name__ == '__main__':
    unittest.main()
